### PR TITLE
Prevented duplicated records to improve populating performance.

### PR DESCRIPTION
**Pull request by jianpingw**
This commit is to fix the slow population (and big memory usage) problem as described in:
https://github.com/balderdashy/sails-mysql/issues/161

Although the issue is for MySQL, it also applies to Postgresql.

### CODE REVIEW

**Comment by particlebanana** [comment]
@jianpingw this is great! Thank you, thank you, thank you!

For anyone checking in here's my tldr:

Postgres and MySql return their data as flat arrays so when populating you get rows with repetitive data in certain columns. 

```
id    |   user   |  pet   |
-------------------------------------------
1     | sam     | fluffy
1     | sam     | scruffy
1     | sam     | bubbles
```

When populating, Waterline takes this and loops through the array building up nested objects along the way. This fixes an issue where it wasn't skipping records that it had already processed (i.e. `sam` in the chart above).

In the test project @jianpingw put together it's the difference between `2332ms` and `116ms`.

**Comment by particlebanana** [comment]
For full circle here's the project showing the performance difference before and after the patch: https://github.com/jianpingw/wl-perf

**Comment by jianpingw** [comment]
For this test case:
https://github.com/jianpingw/wl-perf

The `find messages` test case took about 3000ms on a Core i3-3110M (2.4GHz) HP laptop (the database has zero row before running the test case) before this patch.

With this patch, the same test case took about 200ms.

**Comment by mikermcneil** [comment]
Thanks @jianpingw!

**Comment by mikermcneil** [comment]
@particlebanana btw, [just set up a changelog](https://github.com/balderdashy/sails-postgresql/commit/3e782803c26dae849bf02196a573dd47ebb24dfe) like @Globegitter set up for Sails core and added this as the first change (been working on normalizing this format across our other repos)

**Pull request merged**
