### PR TITLE
Support Soft Deletes in postgresql adapter

### PR DESCRIPTION
**Pull request by polastre**
"Soft Deletes" are commonly used in major database projects to preserve a history of all actions that have occurred.  

I've updated the postgresql adapter in 5 ways:
(1) Add an option called softDelete (default set to false) to enable the softDelete functionality
(2) On table creation, add a new column called deletedAt
(3) On delete, instead of calling DELETE, set deletedAt to the current time NOW()
(4) On find, if softDelete is enabled, add to the where clause a check to filter out non-null deletedAt rows
(5) Add a unit test

Arguably #1 and 2 should be in Waterline and not in the postgresql adapter; however, I didn't want to fork both Waterline and sails-postgresql.  In the case of #2, this would logically reside in schema.js/addAutoAttributes() around line 143.  Putting these in Waterline would require that the other adapters also be updated, which is a larger task.
#4 could be expanded with an additional option (something like showDeleted: true) so that models could be queried for their deleted elements (useful for allowing users to revert accidental deletes).  This would be a future feature request.

### CODE REVIEW

**Comment by Zigur** [comment]
Any news on the soft delete functionality? Are you still planning to add it to sails-postgresql?
For me it would be a worthy addition. 
cheers

**Comment by tjwebb** [comment]
I'm wondering what happens when someone using pg relies on this functionality and then is unable to use other Waterline adapters. All this logic would be basically the same for other adapters.

**Comment by mikermcneil** [comment]
@tjwebb yeah very true-- this belongs as an extension to Waterline core.  @Polastre perhaps we could apply this same strategy to the code in WL core? cc @particlebanana

**Comment by polastre** [comment]
I agree that this belongs in waterline rather than an adapter, but I didn't want to go messing with all of waterline.  Definitely if you put a `softDelete` flag in waterline, it could add `deletedAt` to the schema and amend the queries to only find non-deleted items.  This is definitely the better way to go.

**Comment by particlebanana** [comment]
We need to add a [proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) to the Waterline roadmap for this describing a spec for how it would work at the Waterline level.

**Comment by mikermcneil** [comment]
Addressed by .archive()

**Pull request closed without merging**
