### PR TITLE
Send modified schema to work with wl-sql 0.4.0

### PR DESCRIPTION
**Pull request by particlebanana**
Allows for proper use of tableName.

Should fix balderdashy/waterline#619

### CODE REVIEW

**Comment by dmarcelino** [comment]
I'm good with this :white_check_mark:

**Comment by devinivy** [comment]
Given that this schema-cleansing involves a `cloneDeep` and occurs on every query, I think it really ought to be cached per connection.

**Comment by dmarcelino** [comment]
Well caught @devinivy! Not only you are right I don't think we need `.cloneDeep()` as we are only deleting/adding keys to `schema` so a `.clone()` should suffice (unless I missed something).

**Comment by particlebanana** [comment]
Yeah we can do it once when we instantiate the connection and cache it.

**Comment by particlebanana** [comment]
I'll work on that when I get a chance today.

**Comment by devinivy** [comment]
I think the necessary tools are already there: see https://lodash.com/docs#memoize

**Comment by dmarcelino** [comment]
I wasn't familiar with `.memoize()` and it looks quite useful!

**Comment by devinivy** [comment]
See the proposed fix to the analogous sails-mysql branch: https://github.com/particlebanana/sails-mysql/pull/1
If that goes through, we should repeat here.

**Pull request merged**
