### PR TITLE
Add support for column comments

### PR DESCRIPTION
**Pull request by KyleLilly**
This is related to #197 and adds support for a ```comment``` attribute. The value is returned when calling ```describe```.

### CODE REVIEW

**Comment by devinivy** [comment]
Thanks for your contribution!  Any thoughts @particlebanana / @tjwebb?

**Comment by particlebanana** [comment]
What does this give us? Sorry not familiar with pg comments.

**Comment by tjwebb** [comment]
Postgres has a feature that allows you to annotate columns and tables with
a description of their use/purpose. I think this would be a nice feature,
but IMO it's not very high priority. It'd be awesome if a contributor
wanted to take this on and submit a PR

**Comment by particlebanana** [comment]
https://github.com/BlueHotDog/sails-migrations

I'd like to see all the auto-migration stuff pulled out of Waterline and into a standalone module.

**Comment by devinivy** [comment]
@tjwebb this is that PR :P
@particlebanana are you saying this a "migration" and suggesting the pg comments functionality go somewhere other than this repo?

**Comment by tjwebb** [comment]
@devinivy whoops sorry, I answered via email. It didn't tell me that :(

**Comment by particlebanana** [comment]
@devinivy currently there are no other repos :cry:  but yes. If comments simply annotate the tables in the database then they don't enhance the actual feature set of Waterline. Before, certain things that are only used for migrations have slipped in (indexes, size, etc) but these also provided value to Waterline in that you can see your data structure represented in your models. Replacing:

```javascript
// Stores the foo
foo: {
  type: 'string'
}
```

with

```javascript
foo: {
  type: 'string',
  comment: 'stores the foo'
}
```

doesn't improve Waterline to me. The auto-migrations we have are already a problem for a lot people and people who understand them just turn them off. If we move that heft out to somewhere else that would be nice and actually allow them to be more powerful.

Completely open to discussion though.

**Comment by particlebanana** [comment]
Agreeing with what I said above. I will work on figuring out a solution for migrations that doesn't involve Waterline. We can move the auto-migrate stuff in there too.

**Pull request closed without merging**
