### PR TITLE
Update adapter.js

### PR DESCRIPTION
**Pull request by Ozhvankov**
fix stream function:
change to new query builder
line 930-939 
new Query --> new Sequel

### CODE REVIEW

**Comment by devinivy** [comment]
Hey @Ozhvankov, thanks for your contribution!  A couple questions,

 - The build doesn't pass because `./query` as `require`d doesn't exist inside the repo.
 - Can you explain the change around removing `formattedErr.originalError = err;`?
 - Can you remove unused commented code and `console.log`s?
 - Does this resolve a particular github issue?

**Comment by Ozhvankov** [comment]
bug fix of patch-1
thanx for U "focus" on removing formattedErr.originalError = err;
its our mistake

**Comment by devinivy** [comment]
Just leaving this build failure here, but I think it's a timing issue that needs to be fixed in the adapter tests.  I'm going to re-run the build, and hopefully it will pass.
```
  autoIncrement attribute feature
  ✓ should auto generate unique values
  1) should auto generate unique values even when values have been set
Error (E_VALIDATION) :: 1 attribute is invalid
Error (E_VALIDATION) :: 1 attribute is invalid
error: duplicate key value violates unique constraint "autoIncTable_pkey"
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
Invalid attributes sent to undefined:
 • id
   • A record with that `id` already exists (`5`).
  262 passing (4s)
  2 pending
  1 failing
  1) autoIncrement attribute feature should auto generate unique values even when values have been set:
     [Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undefined:
 • id
   • A record with that `id` already exists (`5`).
  Error (E_VALIDATION) :: 1 attribute is invalid
  Error (E_VALIDATION) :: 1 attribute is invalid
  error: duplicate key value violates unique constraint "autoIncTable_pkey"
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```

**Comment by particlebanana** [comment]
Whoops sorry @Ozhvankov didn't see this. I added #221 which adds the `pg-query-stream` dependency along with these patches. We need to add some tests and get it documented before it can be merged though.

**Pull request closed without merging**
